- README.md
卒業試験 画面遷移図
READMEに画面遷移図のリンクを追記いたしました。  
お手数ですが、ご確認の程よろしくお願いいたします。
Figma  
https://www.figma.com/file/TZELZVG8E9e6JrvN6ppkJ8/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3?type=design&node-id=0%3A1&mode=design&t=n4kMVhFVuAEicfRD-1
以下の項目は適切に未ログインでも閲覧または利用できる画面遷移になっているか？
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移になっているか？
> READMEに画面遷移図のリンクを追記しました

- .rubocop.yml
- config/application.rb
アプリの基本設定を実施
- rails generateコマンドを使用した際に下記のファイルや記述が作成されないよう設定
- helperファイル
- testファイル
- ルーティングの記述
- .rubocop.ymlファイルを生成
> 04 initial setup

- app/views/shared/_before_login_header.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header.html.erb
ヘッダー・フッターの作成
- 以下のビューファイルを作成
- ログイン前のヘッダー
- ログイン後のヘッダー
- フッター
> 06 header footer

- app/controllers/application_controller.rb
- app/controllers/items_controller.rb
- app/controllers/tags_controller.rb
- app/models/item.rb
- app/views/items/collection_items.html.erb
- app/views/items/index.html.erb
- app/views/items/want_items.html.erb
- app/views/shared/_header.html.erb
- config/locales/view.ja.yml
- config/routes.rb
コレクション一覧/欲しいもの一覧機能を作成
- itemsコントローラーのアクション修正
- モデルにスコープ作成
- コレクション一覧/欲しいもの一覧のビューを作成
- tagsコントローラー作成
- タグ絞り込み機能作成
> コレクション一覧/欲しいもの一覧機能を作成

- app/controllers/items_controller.rb
- app/controllers/tags_controller.rb
- app/models/artist_name.rb
- app/models/item.rb
- app/models/title.rb
- app/views/items/collection_items.html.erb
- app/views/items/want_items.html.erb
- config/locales/view.ja.yml
コレクション内/欲しいもの内検索機能を作成
- ビューに検索フォームを作成
- 関連するモデルにRansackの検索を許可する設定
- Tagsコントローラー修正
> コレクション内/欲しいもの内検索機能を作成

- app/controllers/items_controller.rb
- app/models/item.rb
- app/models/release_format.rb
- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
- app/views/releases/show.html.erb
- config/locales/activerecord.ja.yml
- config/locales/view.ja.yml
- db/schema.rb
- fly.toml
- node_modules/.yarn-integrity
- package.json
- yarn.lock
アイテム入力フォームの修正
- release_formatsテーブル/モデル追加
- フォーム/詳細ページにフォーマット項目追加
- 検索結果が入力のフォームに初期値に入るよう変更
- フォームの付属品を複数選択できるよう修正
> アイテム入力フォームの修正

- .gitignore
- config/database.yml
- config/environments/development.rb
- config/environments/production.rb
- docker-compose.yml
- package.json
環境変数の設定を本番用に変更
- 環境変数の設定
- データベース設定
- Webサーバーの設定
- アセットファイルのプリコンパイルを実行
> 環境変数の設定を本番用に変更

- config/database.yml
- docker-compose.yml
ローカルのDB接続設定を変更
ローカルに接続できないエラーが出たため、DB接続設定を変更
> ローカルのDB接続設定を変更

- app/controllers/users_controller.rb
- app/views/profiles/edit.html.erb
- config/locales/view.ja.yml
- config/routes.rb
アカウント削除機能を作成
- Usersコントーラーにdestroyアクションを作成
- ルーティングにdestroyを追加
- アカウント情報編集ページにアカウント削除リンクを追加
- フラッシュメッセージ作成
> アカウント削除機能を作成

- app/views/shared/_footer.html.erb
お問い合せフォームを作成
- Googleフォームでお問い合わせフォームを作成
- お問合せ先をXからGoogleフォームに変更
> お問い合せフォームを作成

- db/migrate/20240625125311_create_shops.rb
- db/schema.rb
shopsテーブルを作成
Google Places APIから取得したショップ情報を保存するテーブルを作成
> shopsテーブルを作成

- app/models/shop.rb
shopモデルにバリデーションを定義
shopモデルにバリデーションを以下の定義
```
validates :name, presence: true
validates :latitude, presence: true
validates :longitude, presence: true
validates :place_id, presence: true
```
> shopモデルにバリデーションを定義

- app/controllers/shops_controller.rb
- app/javascript/controllers/map_controller.js
navigator.geolocation APIを使用してユーザーの位置情報を取得
- navigator.geolocation APIを使用して位置情報を取得・マップの中央に設定
- 位置情報が取得できなかった場合、マップの中央を東京駅付近に設定
- 検索時のズーム設定を変更
> ユーザーの位置情報を取得

- app/controllers/shops_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/javascript/controllers/show_map_controller.js
- app/views/shared/_before_login_header.html.erb
- app/views/shared/_header.html.erb
- app/views/shops/map.html.erb
- app/views/shops/show.html.erb
- config/locales/view.ja.yml
- config/routes.rb
- tailwind.config.js
ショップ詳細機能を作成
- ルーティングとヘルパーメソッドを修正
- ショップ詳細ページ作成
- GoogleMapの経路案内ページへのリンクを追加
> ショップ詳細機能を作成

- app/models/shop.rb
- app/models/shop_bookmark.rb
- app/models/user.rb
- db/migrate/20240827224107_create_shop_bookmarks.rb
- db/schema.rb
shop_bookmarksテーブル/モデルを作成
モデル間のアソシエーションを定義
- shop_bookmarksテーブル作成
- ShopBookmarkモデル作成
- ShopBookmarkを中間テーブルとした、User・Shopモデルとのアソシエーションを定義
> shop_bookmarksテーブル/モデルを作成

- app/controllers/shop_bookmarks_controller.rb
- app/controllers/shops_controller.rb
- app/models/shop.rb
- app/models/user.rb
- app/views/my_pages/show.html.erb
- app/views/shared/_header.html.erb
- app/views/shop_bookmarks/create.turbo_stream.erb
- app/views/shop_bookmarks/destroy.turbo_stream.erb
- app/views/shops/_bookmark.html.erb
- app/views/shops/_bookmark_buttons.html.erb
- app/views/shops/_unbookmark.html.erb
- app/views/shops/bookmarks.html.erb
- app/views/shops/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/locales/view.ja.yml
- config/routes.rb
ショップブックマーク機能・ブックマーク一覧ページ作成
- ショップ詳細ページにブックマークボタンを追加(ログイン時のみ表示)
- ブックマーク機能作成
- ブックマーク一覧ページ作成
- ショップ画像をキャッシュに保存するよう変更
> ショップブックマーク機能を作成

- app/models/review.rb
- app/models/shop.rb
- app/models/user.rb
- db/migrate/20240829090532_create_reviews.rb
- db/schema.rb
reviewsテーブル/モデルを作成
モデル間のアソシエーションを定義
- reviewsテーブル作成
- Reviewモデル作成
- User・Shopモデルとのアソシエーションを定義
> reviewsテーブル/モデルを作成 

- app/controllers/application_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/shops_controller.rb
- app/controllers/user_sessions_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/review_modal_controller.js
- app/views/layouts/application.html.erb
- app/views/reviews/_review.html.erb
- app/views/reviews/new.html.erb
- app/views/shops/show.html.erb
- app/views/static_pages/top.html.erb
- config/locales/view.ja.yml
- config/routes.rb
ショップレビュー機能を作成
ショップ詳細にレビューを表示
- 非同期のモーダルでレビュー投稿フォームを作成
- レビュー投稿機能作成
- ショップ詳細にレビューを表示
- ログイン前後でレビューボタンを出し分け
- ログイン後はログイン直前のURLにリダイレクトするよう変更
> ショップレビュー機能を作成

- app/controllers/reviews_controller.rb
- app/controllers/shops_controller.rb
- app/models/user.rb
- app/views/my_pages/show.html.erb
- app/views/reviews/_review.html.erb
- app/views/reviews/create.turbo_stream.erb
- app/views/reviews/destroy.turbo_stream.erb
- app/views/reviews/edit.html.erb
- app/views/shared/_header.html.erb
- app/views/shops/_review_count.html.erb
- app/views/shops/review_shops.html.erb
- app/views/shops/show.html.erb
- config/locales/view.ja.yml
- config/routes.rb
レビュー編集・削除機能作成
レビューしたショップ一覧機能作成
- レビュー編集削除ボタン追加
- 非同期でのレビュー編集・削除機能作成
- レビューしたショップ一覧機能作成
> レビュー編集・削除機能を作成

- app/views/my_pages/show.html.erb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- app/views/reviews/_review.html.erb
アバターの表示修正/アカウント編集レスポンシブ修正
- アバター画像が元画像のサイズによって歪むバグ修正
- アカウント編集ページのレスポンシブ修正
> UI・レスポンシブ微修正

- app/controllers/application_controller.rb
- app/controllers/search_controller.rb
- app/models/release.rb
- db/schema.rb
アーティスト・リリースタイトル検索機能リファクタリング
- ApplicationControllerとSearchControllerのコードの重複を解消
- Releaseモデルの使用していないクラスメソッドを削除
> アーティスト・リリースタイトル検索機能リファクタリング

- app/controllers/items_controller.rb
Itemsコントローラーリファクタリング
- set_itemメソッドと重複している部分を削除
- set_select_itemsメソッドと重複している部分を削除
> Itemsコントローラーリファクタリング

- app/controllers/reviews_controller.rb
- lib/tasks/import_shops.rake
ショップ関連リファクタリング
- Google Places APからショップ情報を取得するRakeタスクの処理を分割
- Reviewsコントローラーのset_reviewと重複している部分を削除
- set_reviewアクションのレビューの取得範囲を全レビューからユーザー固有のレビューに限定
> ショップ関連リファクタリング

- app/controllers/application_controller.rb
- app/controllers/items_controller.rb
- app/controllers/my_pages_controller.rb
- app/controllers/records_controller.rb
- app/controllers/tags_controller.rb
- app/controllers/users_controller.rb
- app/javascript/controllers/map_controller.js
- app/javascript/controllers/menu_controller.js
- app/javascript/controllers/record_controller.js
- app/models/ability.rb
- app/models/item.rb
- app/services/music_brainz_service.rb
- app/views/shared/_flash_message.html.erb
複数箇所軽微なリファクタリング
- before_action :require_loginを削除
- set_userメソッドにcurrent_user(ヘルパーメソッド)を使用するよう修正
- collection_tag_itemsアクション・want_tag_itemsアクションの共通ロジックをset_tag_dataメソッドに抽出
- set_userメソッドと重複している部分を削除
- メールアドレスを環境変数化
- user && user user&.admin?をuser&.admin?に修正
- 関連オブジェクトの処理部分にコメントを追加
- フラッシュタイプを統一（success → notice、danger → alert）
- _flash_message.html.erbの不要な記述を削除
- record_controller.js
- menu_controller.js
- map_controller.js
> 複数箇所軽微なリファクタリング

- app/models/accessory.rb
- app/models/artist_name.rb
- app/models/condition.rb
- app/models/item.rb
- app/models/matrix_number.rb
- app/models/press_country.rb
- app/models/record.rb
- app/models/release_format.rb
- app/models/review.rb
- app/models/tag.rb
- app/models/title.rb
各入力フォームのカラムに最大値のバリデーションを設定
以下のカラムに最大値のバリデーションを追加
- Accessory / name
- ArtistName / name
- Condition / grede
- MatrixNumber / number
- PressCountry / name
- Tag / name
- Title / name
- ReleaseFormat / name
- Record / content
- Review / content
- Item / user_note
> 各入力フォームのカラムに最大値のバリデーションを設定

- Gemfile
- app/views/items/new.html.erb
- app/views/records/_form.html.erb
- app/views/users/new.html.erb
- config/locales/view.ja.yml
複数箇所軽微なリファクタリング
- 使用していないGem(aws-sdk-s3とcssbundling-rails)削除
- 新規作成時のボタンテキストを「登録」から「保存」に変更し、フォーム送信ボタンの記述をシンプル化
> 複数箇所軽微なリファクタリング 
